# Generated by Django 4.2.4 on 2023-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('ltitle', models.CharField(max_length=100)),
                ('etitle', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('filterby', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('comdate', models.DateField()),
                ('llink', models.URLField()),
                ('glink', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
